apiVersion: apps/v1
kind: Deployment
metadata:
  name: chroma-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chroma-app
  template:
    metadata:
      labels:
        app: chroma-app
    spec:
      containers:
        - name: chroma-app
          image: chroma-app:latest
          # command: ["/bin/sh", "-c"]
          # args: ["python -m uvicorn main:app --host 0.0.0.0 --port 8000"]
          imagePullPolicy: Never # Since we're using local image in minikube
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - KILL
                - MKNOD
                - SYS_CHROOT
          resources: # Specify resource requests and limits
            requests:
              memory: "512Mi"
              cpu: "1000m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "2Gi"
              cpu: "2000m"
              ephemeral-storage: "2Gi"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: chroma-db-volume
              mountPath: /app/data
      volumes:
        - name: chroma-db-volume
          persistentVolumeClaim:
            claimName: chroma-db-pvc
